# Generated by Django 6.0.5 on 2026-05-26 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Создание"),
                            ("update", "Редактирование"),
                            ("delete", "Удаление"),
                            ("block", "Блокировка"),
                            ("unblock", "Разблокировка"),
                            ("sale", "Продажа"),
                            ("book", "Бронирование"),
                            ("cancel", "Отмена брони"),
                            ("expire", "Просрочка брони"),
                            ("complete", "Выдача заказа"),
                            ("other", "Прочее"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.IntegerField(blank=True, null=True)),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
