# Generated by Django 6.0.5 on 2026-05-25 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ensemble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(blank=True, max_length=100)),
                ("founded", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="ensembles/"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Musician",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("biography", models.TextField(blank=True)),
                ("instruments", models.CharField(blank=True, max_length=255)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="musicians/"),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Composition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("duration", models.IntegerField(help_text="Длительность в секундах")),
                (
                    "composer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compositions",
                        to="music.musician",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("исполнитель", "Исполнитель"),
                            ("дирижёр", "Дирижёр"),
                            ("руководитель", "Руководитель"),
                        ],
                        default="исполнитель",
                        max_length=50,
                    ),
                ),
                ("instrument", models.CharField(blank=True, max_length=100)),
                (
                    "ensemble",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="music.ensemble",
                    ),
                ),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="music.musician",
                    ),
                ),
            ],
            options={
                "unique_together": {("musician", "ensemble", "role")},
            },
        ),
    ]
